const fs = require("fs");
const path = require("path");
const { site, forms, grades, finishes, rfqFields, industries, secondaryMaterials, locations, blogPosts, priorityCities, priorityForms, gradeCityPriority } = require("../src/data/site-data");
const { renderPage, escapeHtml } = require("../src/templates/layout");
const root = path.resolve(__dirname, "..");
const pages = [];
function slugify(v){return String(v).toLowerCase().replace(/&/g," and ").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");}
function outPath(slug){return path.join(root,...slug.split("/").filter(Boolean),"index.html");}
function finalUrl(slug){return site.finalDomain.replace(/\/$/,"/")+slug;}
function list(items){return `<ul>${items.map(i=>`<li>${escapeHtml(i)}</li>`).join("")}</ul>`;}
function chips(items, makeSlug){return `<div class="link-chip-grid">${items.map(i=>`<a href="${makeSlug(i)}">${escapeHtml(i.name||i)}</a>`).join("")}</div>`;}
function cardGrid(items, makeSlug, text){return `<div class="page-card-grid">${items.map(i=>`<article class="page-card"><h3><a href="${makeSlug(i)}">${escapeHtml(i.name||i)}</a></h3><p>${escapeHtml(text?text(i):"Share grade, size, quantity and delivery location for a quotation.")}</p></article>`).join("")}</div>`;}
function rfqBlock(){return `<section class="section-pad compact-section"><div class="container two-column"><div><p class="eyebrow">RFQ checklist</p><h2>What to send for a quick quotation</h2><p>Clear details help Bharat Metals check availability, sourceability, processing support and transport feasibility faster.</p></div><div class="info-panel">${list(rfqFields)}</div></div></section>`;}
function ctaBlock(){return `<section class="quote-section"><div class="container quote-grid"><div><p class="eyebrow eyebrow-light">Request a quote</p><h2>Send your stainless steel requirement to Bharat Metals.</h2><p>Call, WhatsApp or email the product form, grade, size, quantity, finish and delivery location.</p></div><div class="button-row"><a class="button button-primary button-on-dark" href="${site.phoneHref}">CALL NOW</a><a class="button button-primary button-on-dark" href="${site.whatsappHref}" target="_blank" rel="noopener">WHATSAPP</a><a class="button button-primary button-on-dark" href="${site.mailto.replace(/&/g,"&amp;")}">EMAIL RFQ</a></div></div></section>`;}
function faqHtml(faq){return `<section class="section-pad"><div class="container faq-layout"><div><p class="eyebrow">Buyer answers</p><h2>Frequently asked questions</h2><p>Short answers for procurement teams, fabricators and project buyers.</p></div><div class="faq-list">${faq.map(f=>`<details><summary>${escapeHtml(f.q)}</summary><p>${escapeHtml(f.a)}</p></details>`).join("")}</div></div></section>`;}
function addPage(page){pages.push(page);}
function pageSection(title,text,extra=""){return `<section class="section-pad compact-section"><div class="container text-flow"><h2>${escapeHtml(title)}</h2><p>${escapeHtml(text)}</p>${extra}</div></section>`;}
function standardFaq(subject){return [
 {q:`Is Bharat Metals a supplier for ${subject}?`,a:`Yes. Bharat Metals can review ${subject} enquiries from its Chennai base based on stock, sourceability, size, quantity and logistics feasibility.`},
 {q:"Which details should I send for a quote?",a:"Send product form, grade, size or thickness, quantity, finish, delivery location, certificate requirement and required date."},
 {q:"Can MTC or mill certificate be discussed?",a:"MTC, mill certificate and third party inspection support can be discussed for applicable stainless steel supplies."},
 {q:"Does Bharat Metals manufacture stainless steel?",a:"No. Bharat Metals uses dealer, stockist, supplier, wholesaler and sourcing support language. It does not claim to manufacture stainless steel."}
];}
function cityByName(name){return locations.find(c=>c.name===name)||locations[0];}
function formBySlug(slug){return forms.find(f=>f.formSlug===slug||f.slug===slug)||forms[0];}
function gradeById(id){return grades.find(g=>g.id===id||g.slug===id)||grades[0];}
function productIntro(form){return `Bharat Metals supports ${form.name.toLowerCase()} enquiries for Chennai, Tamil Nadu and nearby South India buyers. Share ${form.specs}, quantity, delivery location and certificate needs so the team can review stock, sourceability and dispatch options.`;}
function citySlug(city){return `stainless-steel-suppliers-${slugify(city.name)}/`;}
function hubLinks(title,items,makeSlug,pickText){return `<section class="section-pad"><div class="container"><div class="section-heading"><p class="eyebrow">${escapeHtml(title)}</p><h2>Explore related Bharat Metals pages</h2></div>${cardGrid(items,makeSlug,pickText)}</div></section>`;}
function corePage(slug,h1,description,body,breadcrumbs=[]){const faq=standardFaq(h1);addPage({slug,type:"core",title:`${h1} | Bharat Metals Chennai`,description,h1,intro:description,eyebrow:"Company profile",breadcrumbs:[...breadcrumbs,{name:h1,slug}],image:"assets/images/photos/hero/stainless-steel-pipes-stockyard.webp",imageAlt:h1,body:body+faqHtml(faq),faq});}
function buildCorePages(){
 corePage("about-us/","About Bharat Metals","Bharat Metals is a Chennai stainless steel stockist, supplier, dealer and wholesaler established in 1986.",pageSection("Chennai stainless steel supplier since 1986","Bharat Metals works with fabricators, industries, contractors, traders and project buyers who need practical stainless steel supply support from Chennai. The business focus remains stainless steel first, especially for Tamil Nadu and nearby South India markets.")+pageSection("How we work","Buyers can send grade, form, size, finish, quantity, certificate and delivery details. Bharat Metals reviews availability, sourceability, packing, transport booking and documentation support without claiming manufacturer status.")+ctaBlock());
 corePage("mission-vision/","Mission and Vision","Bharat Metals focuses on practical stainless steel supply support for Chennai, Tamil Nadu and nearby markets.",pageSection("Mission","To help stainless steel buyers send clear requirements, choose suitable forms and grades, and receive practical supply guidance from a trusted Chennai market source.")+pageSection("Vision","To keep Bharat Metals recognized as an established stainless steel dealer and stockist in Chennai with modern RFQ-first communication and responsible market coverage."));
 corePage("products/","Product Portfolio","Browse Bharat Metals stainless steel products, grades and selected aluminium, brass and copper sourcing support.",hubLinks("Stainless steel forms",forms,f=>`${f.slug}/`,f=>`${f.name} enquiries by grade, size, finish and quantity.`)+hubLinks("Grades",grades,g=>`${g.slug}/`,g=>`${g.name} material enquiries in forms such as pipes, sheets, plates, rods and bars.`));
 corePage("stainless-steel/","Stainless Steel Products","Bharat Metals focuses on stainless steel pipes, tubes, sheets, plates, coils, rods, bars, flanges and fittings.",pageSection("Stainless steel first","Stainless steel remains the core supply focus. Bharat Metals supports regular enquiries for SS 202, SS 304, SS 316 and other grades across forms used by Chennai and Tamil Nadu industries.",cardGrid(forms,f=>`${f.slug}/`,productIntro))+hubLinks("Popular grades",grades,g=>`${g.slug}/`,g=>g.summary));
 corePage("industries-we-serve/","Industries We Serve","Bharat Metals supports stainless steel enquiries for fabrication, engineering, kitchen equipment, pharma, food processing, marine and other industries.",hubLinks("Industry pages",industries,i=>`industries/${i.slug}/`,i=>`Common products: ${i.products.join(", ")}.`));
 corePage("locations-we-serve/","Locations We Serve","Bharat Metals is Chennai-based and supports stainless steel enquiries across Tamil Nadu and nearby South India markets.",pageSection("Supply support from Chennai","Bharat Metals does not claim branch offices in other cities. Enquiries are reviewed from Chennai based on product availability, quantity and logistics feasibility.",cardGrid(locations.slice(0,60),citySlug,c=>`${c.region} - ${c.profile}.`))+hubLinks("More locations",locations.slice(60),citySlug,c=>`${c.region} stainless steel supply enquiry support.`));
 corePage("request-quote/","Request a Stainless Steel Quote","Send product form, grade, size, finish, quantity and delivery location to Bharat Metals for a stainless steel quotation.",rfqBlock()+ctaBlock());
 corePage("contact-us/","Contact Bharat Metals","Contact Bharat Metals in Chennai for stainless steel pipes, sheets, plates, rods, bars, flanges and fittings.",pageSection("Chennai address",site.addressLines.join(" "))+ctaBlock());
 corePage("technical-data/","Technical Data","Technical reference hub for stainless steel grades, finishes, RFQ details and buyer checklist pages.",pageSection("Technical notes","This section gives buyer-friendly reference content. It avoids unsupported engineering claims and asks buyers to share application, grade, size and certificate needs.",`<div class="data-table"><table><thead><tr><th>Reference</th><th>Use</th></tr></thead><tbody><tr><td>Grades</td><td>Compare SS 202, 304, 316 and other common grades.</td></tr><tr><td>Finishes</td><td>Describe 2B, No. 1, BA, mirror, matt, hairline, brush and PVC coated sheet needs.</td></tr><tr><td>Certificates</td><td>Ask for MTC, mill certificate or inspection where applicable.</td></tr></tbody></table></div>`));
 corePage("blog/","Bharat Metals Blog","Buyer guides for stainless steel grades, product forms, finishes, certificates and city supply support.",hubLinks("Blog articles",blogPosts,b=>`blog/${b.slug}/`,b=>b.summary));
 for(const material of Object.keys(secondaryMaterials)){const title=material[0].toUpperCase()+material.slice(1);corePage(`${material}/`,`${title} Sourcing Support`,`${title} is a secondary commercial sourcing category at Bharat Metals, available based on stock, sourceability, size and quantity.`,pageSection(`${title} is secondary`,`While stainless steel remains the core supply focus, Bharat Metals can review selected ${material} enquiries based on stock, sourceability, size and quantity.`,cardGrid(secondaryMaterials[material],item=>`${material}-${slugify(item)}/`,item=>`${title} ${item.toLowerCase()} enquiry support where sourceable.`)));}
 [["contacts-us/","Legacy Contact Bharat Metals","Legacy contact URL for Bharat Metals stainless steel enquiries in Chennai."],["ss-chemical/","Stainless Steel Chemical Composition Notes","Legacy stainless steel chemical reference page with safe buyer guidance."],["ss-mechanical/","Stainless Steel Mechanical Property Notes","Legacy stainless steel mechanical reference page for buyer discussions."],["ss-physical/","Stainless Steel Physical Property Notes","Legacy stainless steel physical property page for buyer reference."],["ss-types-and-applications/","Stainless Steel Types and Applications","Legacy stainless steel type and application guide for Bharat Metals buyers."]].forEach(([slug,h1,desc])=>corePage(slug,h1,desc,pageSection("Legacy SEO compatibility","This page preserves an older stainless steel reference path while pointing buyers to current Bharat Metals product, grade and RFQ pages.")+hubLinks("Useful current pages",["stainless-steel/","technical-data/","request-quote/","contact-us/"],s=>s,s=>`Open ${s.replace(/\//g,"")||"home"}.`)));
}
function buildProductPages(){forms.forEach(form=>{const faq=standardFaq(form.name).concat([{q:`Which grades are common for ${form.short.toLowerCase()}?`,a:"Common enquiries include SS 202, SS 304 and SS 316, with 304L, 316L, 310, 410, 420 and 430 reviewed where suitable."}]);addPage({slug:`${form.slug}/`,type:"product",title:`${form.name} in Chennai | Bharat Metals`,description:`${form.name} supplier enquiry support in Chennai for Tamil Nadu buyers. Share ${form.specs}, grade, quantity and delivery location.`,h1:`${form.name} Suppliers in Chennai`,eyebrow:"Stainless steel product",intro:productIntro(form),image:form.image,imageAlt:`${form.name} stock for Bharat Metals buyers`,breadcrumbs:[{name:"Products",slug:"products/"},{name:form.name,slug:`${form.slug}/`}],body:pageSection("Product overview",`${form.name} are requested by fabricators, contractors, traders and industrial buyers. Bharat Metals reviews enquiries with grade, size, finish, quantity and transport details before confirming availability or sourceability.`)+pageSection("Applications",`${form.name} are commonly discussed for ${form.uses.join(", ")}. The exact grade and finish should be chosen based on exposure, fabrication method, hygiene needs and buyer specification.`,`<h3>Common grades</h3>${chips(grades,g=>`${g.slug}/`)}<h3>Useful finish options</h3>${list(finishes.slice(0,8))}`)+hubLinks("Related locations",locations.slice(0,12),citySlug,c=>`${c.name} buyers can send ${form.short.toLowerCase()} enquiries from Chennai.`)+rfqBlock()+ctaBlock()+faqHtml(faq),faq});});}
function buildGradePages(){grades.forEach(grade=>{const faq=standardFaq(grade.name).concat([{q:`Which forms are available in ${grade.name}?`,a:`${grade.name} enquiries can be reviewed for pipes, sheets, plates, coils, rods, bars, flanges, fittings and other forms depending on stock and sourceability.`}]);addPage({slug:`${grade.slug}/`,type:"grade",title:`${grade.name} Suppliers in Chennai | Bharat Metals`,description:`${grade.name} stainless steel enquiry support in Chennai for pipes, sheets, plates, rods, bars and fittings.`,h1:`${grade.name} Stainless Steel Suppliers in Chennai`,eyebrow:"Stainless steel grade",intro:`${grade.name} is ${grade.summary}. Bharat Metals reviews ${grade.name} requirements from Chennai with form, size, finish, quantity and certificate details.`,image:"assets/images/photos/materials/stainless-steel.webp",imageAlt:`${grade.name} stainless steel material`,breadcrumbs:[{name:"Stainless Steel",slug:"stainless-steel/"},{name:grade.name,slug:`${grade.slug}/`}],body:pageSection("Grade overview",`${grade.name} material enquiries should include application, form, size, finish and quantity. ${grade.notes}`)+hubLinks("Available forms",forms,f=>`${grade.slug}-${f.formSlug}/`,f=>`${grade.name} ${f.short.toLowerCase()} enquiry support.`)+hubLinks("Industries using this grade",industries.slice(0,10),i=>`industries/${i.slug}/`,i=>`Common products include ${i.products.join(", ")}.`)+rfqBlock()+ctaBlock()+faqHtml(faq),faq});});}
function buildGradeFormPages(){grades.forEach(grade=>forms.forEach(form=>{const subject=`${grade.name} ${form.short}`;const faq=[{q:`Can Bharat Metals supply ${subject} in Chennai?`,a:`Bharat Metals can review ${subject} enquiries from Chennai based on stock, sourceability, size, quantity, finish and logistics feasibility.`},{q:`What details are needed for ${subject}?`,a:`Send ${form.specs}, quantity, finish, delivery location and certificate requirement.`},{q:`Where is ${subject} commonly used?`,a:`${subject} is commonly discussed for ${form.uses.join(", ")} depending on application suitability.`},{q:"Can delivery outside Chennai be discussed?",a:"Yes. Delivery or transport booking can be discussed for Tamil Nadu and nearby regions based on order details."},{q:"Does Bharat Metals manufacture this material?",a:"No. Bharat Metals is a stainless steel dealer, stockist, supplier, wholesaler and sourcing support business."}];addPage({slug:`${grade.slug}-${form.formSlug}/`,type:"grade-form",title:`${subject} Suppliers in Chennai | Bharat Metals`,description:`${subject} enquiry support in Chennai with grade, size, finish, quantity, certificate and transport details.`,h1:`${subject} Suppliers in Chennai`,eyebrow:"Grade and product form",intro:`${subject} enquiries are reviewed by Bharat Metals from Chennai for fabricators, contractors, traders and industrial buyers. Share ${form.specs} for a practical response.`,image:form.image,imageAlt:`${subject} material`,breadcrumbs:[{name:grade.name,slug:`${grade.slug}/`},{name:form.name,slug:`${form.slug}/`},{name:subject,slug:`${grade.slug}-${form.formSlug}/`}],body:pageSection(`${subject} overview`,`${grade.name} is ${grade.summary}. In ${form.short.toLowerCase()} form, buyers usually need clear size, finish, quantity and application details before availability can be reviewed.`)+pageSection("Applications and industries",`${subject} may be requested for ${form.uses.join(", ")}. Common buyer groups include fabricators, engineering companies, machine shops, contractors, traders and maintenance teams.`,`<h3>Related industries</h3>${chips(industries.slice(0,8),i=>`industries/${i.slug}/`)}`)+pageSection("Supply note","Bharat Metals is Chennai-based and supports Tamil Nadu and nearby South India enquiries depending on product availability, quantity and transport feasibility.")+rfqBlock()+ctaBlock()+faqHtml(faq),faq});}));}
function buildLocationPages(){locations.forEach(city=>{const slug=citySlug(city);const faq=[{q:`Does Bharat Metals have a branch in ${city.name}?`,a:`No branch office is claimed in ${city.name}. Bharat Metals is Chennai-based and reviews enquiries for ${city.name} from Chennai based on availability and logistics feasibility.`},{q:`Which stainless steel products are popular for ${city.name}?`,a:`Common ${city.name} enquiries include ${city.products.join(", ")} depending on buyer type and application.`},{q:`Which grades are commonly discussed for ${city.name}?`,a:`Common grades include ${city.grades.join(", ")} based on corrosion exposure, fabrication need and buyer specification.`},{q:"What should I send for a quick quote?",a:"Send product form, grade, size, quantity, finish, delivery location, certificate requirement and required date."}];addPage({slug,type:"location",title:`Stainless Steel Suppliers in ${city.name} | Bharat Metals`,description:`Bharat Metals supports stainless steel enquiries for ${city.name} from Chennai with products such as ${city.products.slice(0,4).join(", ")}.`,h1:`Stainless Steel Suppliers in ${city.name}`,eyebrow:`${city.region} supply support`,intro:`Bharat Metals supports enquiries and dispatches from Chennai to buyers in ${city.name} based on product availability, quantity and logistics feasibility.`,image:city.region==="Nearby export"?"assets/images/photos/industries/industrial-plant.webp":"assets/images/photos/hero/stainless-steel-pipes-stockyard.webp",imageAlt:`Stainless steel supply support for ${city.name}`,breadcrumbs:[{name:"Locations",slug:"locations-we-serve/"},{name:city.name,slug}],body:pageSection(`${city.name} industrial profile`,`${city.name} has ${city.profile}. Buyers commonly ask for stainless steel by form, grade, size and finish rather than only by generic material name.`)+pageSection("Popular products and grades",`For ${city.name}, Bharat Metals commonly reviews enquiries for ${city.products.join(", ")}. Grades often discussed include ${city.grades.join(", ")}.`,`<h3>Related products</h3>${chips(forms.slice(0,8),f=>`${f.slug}/`)}<h3>Related grades</h3>${chips(grades.slice(0,5),g=>`${g.slug}/`)}`)+pageSection("Delivery and transport guidance",`Bharat Metals is Chennai-based. For ${city.name}, dispatch, door delivery, transport booking or courier for small items can be discussed after product availability, quantity, packing and required date are clear.`)+rfqBlock()+ctaBlock()+faqHtml(faq),faq});});}
function buildIndustryPages(){industries.forEach(industry=>{const faq=standardFaq(industry.name).concat([{q:`Which grades suit ${industry.name}?`,a:`Common grades discussed for ${industry.name} include ${industry.grades.join(", ")} depending on exposure, fabrication and documentation needs.`}]);addPage({slug:`industries/${industry.slug}/`,type:"industry",title:`${industry.name} Stainless Steel Suppliers | Bharat Metals`,description:`Stainless steel supply support for ${industry.name}: ${industry.products.join(", ")} and grades such as ${industry.grades.join(", ")}.`,h1:`Stainless Steel for ${industry.name}`,eyebrow:"Industry supply support",intro:`Bharat Metals reviews stainless steel enquiries for ${industry.name} buyers from Chennai with practical product, grade, finish and documentation guidance.`,image:"assets/images/photos/industries/industrial-plant.webp",imageAlt:`${industry.name} industrial stainless steel supply`,breadcrumbs:[{name:"Industries",slug:"industries-we-serve/"},{name:industry.name,slug:`industries/${industry.slug}/`}],body:pageSection("Industry overview",`${industry.name} buyers may need stainless steel for fabrication, maintenance, equipment, installation or project supply. Bharat Metals helps buyers describe requirements clearly before checking availability or sourceability.`)+pageSection("Common products",`Common products for ${industry.name} include ${industry.products.join(", ")}. Common grades discussed include ${industry.grades.join(", ")}.`,`<h3>Related products</h3>${chips(forms.slice(0,8),f=>`${f.slug}/`)}`)+pageSection("Documentation and services",`Cutting, polishing, packing, transport booking, MTC, mill certificate and third party inspection can be discussed where applicable for ${industry.name} enquiries.`)+rfqBlock()+ctaBlock()+faqHtml(faq),faq});});}
function buildSecondaryPages(){Object.entries(secondaryMaterials).forEach(([material,items])=>{const title=material[0].toUpperCase()+material.slice(1);items.forEach(item=>{const slug=`${material}-${slugify(item)}/`;const h1=`${title} ${item} Sourcing Support`;const faq=standardFaq(`${title} ${item}`).concat([{q:`Are ${title} ${item.toLowerCase()} a core focus?`,a:`No. ${title} ${item.toLowerCase()} are secondary commercial/sourceable items. Stainless steel remains the core Bharat Metals supply focus.`}]);addPage({slug,type:"secondary",title:`${title} ${item} in Chennai | Bharat Metals`,description:`${title} ${item.toLowerCase()} are secondary commercial sourcing items at Bharat Metals, available based on stock, sourceability, size and quantity.`,h1,eyebrow:"Secondary material",intro:`While stainless steel remains the core supply focus, Bharat Metals can review selected ${title} ${item.toLowerCase()} enquiries based on stock, sourceability, size and quantity.`,image:null,breadcrumbs:[{name:title,slug:`${material}/`},{name:item,slug}],body:pageSection("Secondary sourcing note",`${title} ${item.toLowerCase()} are not positioned as a primary Bharat Metals category. Share size, grade or alloy if known, quantity and delivery location so sourceability can be checked.`)+rfqBlock()+ctaBlock()+faqHtml(faq),faq});});});}
function buildCityProductPages(){priorityCities.forEach(name=>priorityForms.forEach(formSlug=>{const city=cityByName(name);const form=formBySlug(formSlug);const slug=`${form.slug}-${slugify(city.name)}/`;const subject=`${form.name} in ${city.name}`;const faq=standardFaq(subject);addPage({slug,type:"city-product",title:`${form.short} ${city.name} Supply Support | Bharat Metals`,description:`${subject} enquiry support from Chennai for ${city.profile}.`,h1:subject,eyebrow:"City and product",intro:`Bharat Metals supports ${form.short.toLowerCase()} enquiries for ${city.name} buyers from Chennai based on availability, quantity and logistics feasibility.`,image:form.image,imageAlt:subject,breadcrumbs:[{name:city.name,slug:citySlug(city)},{name:form.name,slug:`${form.slug}/`},{name:subject,slug}],body:pageSection(`${city.name} relevance`,`${city.name} has ${city.profile}. ${form.name} may be requested by fabricators, contractors, industries, traders and project buyers depending on the application.`)+pageSection("Grades and RFQ notes",`Common grades discussed for ${city.name} include ${city.grades.join(", ")}. Send ${form.specs}, quantity, finish and delivery location for a practical quotation response.`)+rfqBlock()+ctaBlock()+faqHtml(faq),faq});}));}
function buildGradeCityPages(){["202","304","316"].forEach(gid=>gradeCityPriority.forEach(name=>{const grade=gradeById(gid);const city=cityByName(name);const slug=`${grade.slug}-suppliers-${slugify(city.name)}/`;const subject=`${grade.name} Suppliers in ${city.name}`;const faq=standardFaq(subject);addPage({slug,type:"grade-city",title:`${grade.name} ${city.name} Supply Support | Bharat Metals`,description:`${grade.name} stainless steel enquiry support for ${city.name} from Chennai with product form, size, finish and quantity details.`,h1:subject,eyebrow:"Grade and city",intro:`Bharat Metals reviews ${grade.name} stainless steel enquiries for ${city.name} buyers from Chennai based on stock, sourceability, quantity and logistics feasibility.`,image:"assets/images/photos/materials/stainless-steel.webp",imageAlt:subject,breadcrumbs:[{name:grade.name,slug:`${grade.slug}/`},{name:city.name,slug:citySlug(city)},{name:subject,slug}],body:pageSection(`${grade.name} for ${city.name}`,`${city.name} has ${city.profile}. ${grade.name} is ${grade.summary}. Buyers should send the exact form, size and application so the enquiry can be reviewed responsibly.`)+pageSection("Forms available",`${grade.name} enquiries can be discussed for ${forms.slice(0,10).map(f=>f.short).join(", ")} and other forms depending on availability.`,chips(forms.slice(0,10),f=>`${grade.slug}-${f.formSlug}/`))+rfqBlock()+ctaBlock()+faqHtml(faq),faq});}));}
function buildBlogPages(){blogPosts.forEach(post=>{const faq=[{q:"Can Bharat Metals help with this topic?",a:"Yes. Bharat Metals can review practical stainless steel enquiries when product form, grade, size, quantity and delivery location are clear."},{q:"Is this a substitute for engineering design advice?",a:"No. These notes are buyer guidance. Critical applications should be checked with the project engineer or specification owner."}];addPage({slug:`blog/${post.slug}/`,type:"blog",title:`${post.title} | Bharat Metals Blog`,description:post.summary,h1:post.title,eyebrow:"Buyer guide",intro:post.summary,image:"assets/images/photos/materials/stainless-steel.webp",imageAlt:post.title,breadcrumbs:[{name:"Blog",slug:"blog/"},{name:post.title,slug:`blog/${post.slug}/`}],body:pageSection("Buyer summary",`${post.summary} Bharat Metals writes these notes for fabricators, contractors, traders, industrial buyers and project teams who want clearer stainless steel quotation conversations.`)+pageSection("Practical guidance","Start with the application and environment, then confirm product form, grade, size, finish, quantity, certificate requirement and delivery location. For Jindal make or other reputed mill material, availability can be discussed based on requirement; no authorized dealer claim is made.")+pageSection("How to use this guide","Use the article as a checklist before contacting a supplier. The better the RFQ details, the easier it is to review availability, sourceability, packing, transport and documentation.",`<h3>Useful links</h3>${chips(["request-quote/","stainless-steel/","ss-304/","ss-316/"],s=>s)}`)+rfqBlock()+ctaBlock()+faqHtml(faq),faq});});}
function updateHomepageLinks(){
 const file=path.join(root,"index.html"); let html=fs.readFileSync(file,"utf8");
 const reps=[
  ['href="#top">HOME','href="./">HOME'],['href="#why-choose">About Us','href="about-us/">About Us'],['href="#why-choose">Mission and Vision','href="mission-vision/">Mission and Vision'],['href="#industries">Industries We Serve','href="industries-we-serve/">Industries We Serve'],['href="#regional-support">Locations We Serve','href="locations-we-serve/">Locations We Serve'],['href="#materials">Stainless Steel','href="stainless-steel/">Stainless Steel'],['href="#materials">Aluminium','href="aluminium/">Aluminium'],['href="#materials">Brass','href="brass/">Brass'],['href="#materials">Copper','href="copper/">Copper'],['href="#request-quote">REQUEST A QUOTE','href="request-quote/">REQUEST A QUOTE'],['href="#seo-searches">BLOG','href="blog/">BLOG'],['href="#contact">CONTACT US','href="contact-us/">CONTACT US'],['href="#technical-data">Technical Data','href="technical-data/">Technical Data'],['href="#request-quote">Request a Quote','href="request-quote/">Request a Quote'],['href="#seo-searches">Blog','href="blog/">Blog'],['href="#product-forms">Stainless Steel Pipes','href="stainless-steel-pipes/">Stainless Steel Pipes'],['href="#product-forms">Stainless Steel Sheets','href="stainless-steel-sheets/">Stainless Steel Sheets'],['href="#product-forms">Stainless Steel Plates','href="stainless-steel-plates/">Stainless Steel Plates'],['href="#product-forms">Stainless Steel Coils','href="stainless-steel-coils/">Stainless Steel Coils'],['href="#product-forms">Stainless Steel Rods &amp; Bars','href="stainless-steel-rods/">Stainless Steel Rods &amp; Bars'],['href="#product-forms">Flanges &amp; Fittings','href="stainless-steel-flanges/">Flanges &amp; Fittings'],['href="#regional-support">Chennai','href="stainless-steel-suppliers-chennai/">Chennai'],['href="#regional-support">Coimbatore','href="stainless-steel-suppliers-coimbatore/">Coimbatore'],['href="#regional-support">Madurai','href="stainless-steel-suppliers-madurai/">Madurai'],['href="#regional-support">Trichy','href="stainless-steel-suppliers-trichy/">Trichy'],['href="#regional-support">Salem','href="stainless-steel-suppliers-salem/">Salem'],['href="#regional-support">Hosur','href="stainless-steel-suppliers-hosur/">Hosur'],['href="#regional-support">Pondicherry','href="stainless-steel-suppliers-pondicherry/">Pondicherry']
 ];
 for(const [from,to] of reps) html=html.replaceAll(from,to);
 html=html.replace(`<!-- TODO: Replace with real approved photo: assets/images/photos/hero/stainless-steel-pipes-stockyard.webp -->\n            <div class="photo-placeholder hero-photo-placeholder" role="img" aria-label="Photo pending: stainless steel pipes stockyard">\n              <span>Photo pending</span>\n            </div>`,`<img src="assets/images/photos/hero/stainless-steel-pipes-stockyard.webp" alt="Stainless steel pipes stockyard for Bharat Metals Chennai" width="500" height="312" fetchpriority="high">`);
 html=html.replace(`<!-- TODO: Replace with real approved photo: assets/images/photos/materials/stainless-steel.webp -->\n              <div class="photo-placeholder" role="img" aria-label="Photo pending: stainless steel material stock">\n                <span>Photo pending</span>\n              </div>`,`<img src="assets/images/photos/materials/stainless-steel.webp" alt="Stainless steel pipes and material stock" width="500" height="333" loading="lazy">`);
 fs.writeFileSync(file,html);
}
function generate(){
 buildCorePages(); buildProductPages(); buildGradePages(); buildGradeFormPages(); buildLocationPages(); buildIndustryPages(); buildSecondaryPages(); buildCityProductPages(); buildGradeCityPages(); buildBlogPages();
 const seen=new Set(); const unique=[]; for(const page of pages){if(seen.has(page.slug)) throw new Error(`Duplicate page slug: ${page.slug}`); seen.add(page.slug); unique.push(page);}
 unique.forEach(page=>{const html=renderPage(site,page); const target=outPath(page.slug); fs.mkdirSync(path.dirname(target),{recursive:true}); fs.writeFileSync(target,html);});
 updateHomepageLinks();
 const urls=[{slug:"",priority:"1.0"},...unique.map(p=>({slug:p.slug,priority:p.type==="core"?"0.9":p.type==="location"?"0.7":"0.8"}))];
 const sitemap=`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(u=>`  <url>\n    <loc>${finalUrl(u.slug)}</loc>\n    <lastmod>2026-07-03</lastmod>\n    <changefreq>weekly</changefreq>\n    <priority>${u.priority}</priority>\n  </url>`).join("\n")}\n</urlset>\n`;
 fs.writeFileSync(path.join(root,"sitemap.xml"),sitemap); fs.writeFileSync(path.join(root,"robots.txt"),`User-agent: *\nAllow: /\n\nSitemap: ${site.finalDomain}sitemap.xml\n`);
 const byType=unique.reduce((acc,p)=>{acc[p.type]=(acc[p.type]||0)+1;return acc;},{});
 fs.mkdirSync(path.join(root,"reports"),{recursive:true}); fs.writeFileSync(path.join(root,"reports","mega-sprint-pages.json"),JSON.stringify({generatedAt:"2026-07-03",totalPages:unique.length+1,generatedPages:unique.length,byType,urls:urls.map(u=>finalUrl(u.slug))},null,2));
 console.log(`Generated ${unique.length} pages plus homepage. Sitemap URLs: ${urls.length}`); console.log(JSON.stringify(byType,null,2));
}
generate();
